# Generated by Django 5.0.1 on 2024-02-05 05:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название категории расхода')),
            ],
            options={
                'verbose_name': 'Категория расхода',
                'verbose_name_plural': 'Категории для расхода',
            },
        ),
        migrations.CreateModel(
            name='IncomeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Категория дохода',
                'verbose_name_plural': 'Категория доходов',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма расхода')),
                ('date', models.DateField(verbose_name='Дата расхода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание расхода')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.expensecategory', verbose_name='Категория расхода')),
            ],
            options={
                'verbose_name': 'Разход',
                'verbose_name_plural': 'Расходы',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма дохода')),
                ('date', models.DateField(verbose_name='Дата получения дохода')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание дохода')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.incomecategory', verbose_name='Категория дохода')),
            ],
            options={
                'verbose_name': 'Доход',
                'verbose_name_plural': 'Доходы',
            },
        ),
    ]
